name: Build and Deploy Spring Boot App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build with Maven
      run: mvn clean package

    - name: Build Docker image
      run: |
        docker build -t tu-usuario-dockerhub/api_deployment:latest .

    - name: Login to Docker Hub
      run: |
        docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} -p ${{ secrets.DOCKER_HUB_PASSWORD }}
      # The 'if' condition using secrets is not supported here and has been removed.

    - name: Push Docker image to Docker Hub
      run: |
        docker push tu-usuario-dockerhub/api_deployment:latest